source 'https://rubygems.org'

gem 'ProMotion', :git => 'git@github.com:clearsightstudio/ProMotion.git', :branch => 'version-1.0'
gem 'motion-cocoapods'
gem 'teacup'
gem 'motion-pixate'

group :development do
  gem 'motion-redgreen'
  gem 'motion-stump'
  gem 'webstub'
end
